### ISSUE TITLE
Error trying to import Keras model, AttributeError: 'NoneType' object has no attribute 'GetInputShape'

### ISSUE THREAD

**Issue by stanlee321** [Microsoft/ELL#119]
Dear Team Hi!, I getting this error trying to convert a Keras model to a .ell model using all the doc that I found.

First I use this code  "from the keras examples" to ouput a Keras  .h5 model (CNTK backend)
```
'''
mnist_mlp.py
Trains a simple deep NN on the MNIST dataset.

Gets to 98.40% test accuracy after 20 epochs
(there is *a lot* of margin for parameter tuning).
2 seconds per epoch on a K520 GPU.
'''
from __future__ import print_function

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
from keras.models import load_model
batch_size = 128
num_classes = 10
epochs = 20

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = Sequential()
model.add(Dense(units = 512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(units = 256, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)

model.save('my_mnist_mlp_model.h5')

print('Test loss:', score[0])
print('Test accuracy:', score[1])

```

to then convert to a  CNTK model ```.cntk``` with this piece of code:

```
import cntk
from keras.models import load_model
keras_model = load_model('my_mnist_mlp_model.h5')
cntk.combine(keras_model.model.outputs).save('my_mnist_cntk_model.cntk')
cntk_model = cntk.load_model('my_mnist_cntk_model.cntk')
print('model loaded successfully. ', type(cntk_model))
```
which ouputs   ```my_mnist_cntk_model.cntk``` 

nd later to a ELL ```.ell``` model  with:

```
(cntk) stanlee321@stanlee321-MS-7693:~/Desktop/ELL$ python ./ELL/tools/importers/CNTK/cntk_import.py my_mnist_cntk_model 
Loading...
Selected GPU[0] GeForce GTX 750 Ti as the process wide default device.

Finished loading.
Pre-processing...

Will not process Reshape - empty input shape.

Will not process Reshape - empty input shape.

Will not process Reshape - empty input shape.

Will not process Times - skipping this layer as irrelevant.

Will not process Plus - Only processing Plus functions that act as bias layers

Will not process Dropout - skipping this layer as irrelevant.

Will not process Select - skipping this layer as irrelevant.

Will not process Times - skipping this layer as irrelevant.

Will not process Plus - Only processing Plus functions that act as bias layers

Will not process Dropout - skipping this layer as irrelevant.

Will not process Select - skipping this layer as irrelevant.

Will not process Times - skipping this layer as irrelevant.

Will not process Plus - Only processing Plus functions that act as bias layers

Will not process Combine - skipping this layer as irrelevant.
ReLU :  1x1x512  ->  1x1x512 | input padding 0  output padding 0
ReLU :  1x1x256  ->  1x1x256 | input padding 0  output padding 0
Softmax :  1x1x10  ->  1x1x10 | input padding 0  output padding 0

Finished pre-processing.
Error occurred attempting to convert cntk layers to ELL layers
Traceback (most recent call last):
  File "/home/stanlee321/Desktop/ELL/ELL/tools/importers/CNTK/cntk_to_ell.py", line 50, in predictor_from_cntk_model
    predictor = ELL.FloatNeuralNetworkPredictor(ellLayers)
  File "/home/stanlee321/Desktop/ELL/ELL/build/interfaces/python/ELL.py", line 4448, in __init__
    this = _ELL.new_FloatNeuralNetworkPredictor(layers, scaleFactor)
ValueError: Input tensor must not exceed output tensor (minus padding) dimensions for activation layer.
Traceback (most recent call last):
  File "./ELL/tools/importers/CNTK/cntk_import.py", line 65, in <module>
    main(argv)
  File "./ELL/tools/importers/CNTK/cntk_import.py", line 46, in main
    input_shape = predictor.GetInputShape()
AttributeError: 'NoneType' object has no attribute 'GetInputShape'

```
And I get the error from above.

but with the mnist.cntk created by the script  in ``` /ELL/CNTK/Examples/Image/Classification/MLP/Python/SimpleMNIST.py ```
 all goes flawless
```
(cntk) stanlee321@stanlee321-MS-7693:~/Desktop/ELL$ python ./ELL/tools/importers/CNTK/cntk_import.py mnist.cntk 
Loading...
Selected GPU[0] GeForce GTX 750 Ti as the process wide default device.

Finished loading.
Pre-processing...
ElementTimes :  1x1x784  ->  1x1x784 | input padding 0  output padding 0
Dense :  1x1x784  ->  1x1x200 | input padding 0  output padding 0
Dense :  1x1x200  ->  1x1x10 | input padding 0  output padding 0

Finished pre-processing.
Saving model file: 'mnist.ell'
```
This has relation with the
``` 
Known issues

    Performance optimization on CPU device in combination with Keras is an ongoing work item.

    Currently not supported: Gradient as symbolic ops, stateful recurrent layer, masking on recurrent layer, padding with non-specified shape (to use the CNTK backend in Keras with padding, please specify a well-defined input shape), convolution with dilation, randomness op across batch axis, few backend APIs such as reverse, top_k, ctc, map, foldl, foldr, etc.

```
in your page
https://docs.microsoft.com/en-us/cognitive-toolkit/using-cntk-with-keras

????????????????????

**Comment by lisaong** [comment]
As you noted, there's some incompatibility between how the Dense layers are being converted from Keras to CNTK, because the model imports to ELL fine if constructed using CNTK directly.

This will require some debugging to compare the two models.  Maybe the attributes on the Dense layer are set up differently for the Keras-imported model.
