### ISSUE TITLE
Import model from CNTK fails: No module named_ell_py

### ISSUE THREAD

**Issue by julian0001** [Microsoft/ELL#160]
By running the importer script I get the following output and error code:

C:\Users\Julian\OneDrive\ELL>python ELL/tools/importers/CNTK/cntk_import.py model.cntk
Traceback (most recent call last):
  File "C:\Users\Julian\OneDrive\ELL\ELL\build\interfaces\python\package\ell\ell_py.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ProgramData\Miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ell._ell_py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ELL/tools/importers/CNTK/cntk_import.py", line 24, in <module>
    import cntk_to_ell
  File "C:\Users\Julian\OneDrive\ELL\ELL\tools\importers\CNTK\cntk_to_ell.py", line 23, in <module>
    import ell
  File "C:\Users\Julian\OneDrive\ELL\ELL\build\interfaces\python\package\ell\__init__.py", line 19, in <module>
    from . import data
  File "C:\Users\Julian\OneDrive\ELL\ELL\build\interfaces\python\package\ell\data\__init__.py", line 9, in <module>
    from ..ell_py import AutoDataVector, \
  File "C:\Users\Julian\OneDrive\ELL\ELL\build\interfaces\python\package\ell\ell_py.py", line 17, in <module>
    _ell_py = swig_import_helper()
  File "C:\Users\Julian\OneDrive\ELL\ELL\build\interfaces\python\package\ell\ell_py.py", line 16, in swig_import_helper
    return importlib.import_module('_ell_py')
  File "C:\ProgramData\Miniconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_ell_py'

Any solutions?

**Comment by julian0001** [comment]
Does anyone have the same issue with the python ell binding??

**Comment by julian0001** [comment]
Output of ctest:

(py36) C:\Users\Julian\Documents\ELL\ELL.git\trunk\build>ctest --build-config Release
Test project C:/Users/Julian/Documents/ELL/ELL.git/trunk/build
      Start  1: common_test
 1/36 Test  #1: common_test ......................   Passed    0.29 sec
      Start  2: data_test
 2/36 Test  #2: data_test ........................   Passed    0.03 sec
      Start  3: dsp_test
 3/36 Test  #3: dsp_test .........................   Passed    3.62 sec
      Start  4: emitters_test
 4/36 Test  #4: emitters_test ....................   Passed    0.25 sec
      Start  5: evaluators_test
 5/36 Test  #5: evaluators_test ..................   Passed    0.03 sec
      Start  6: functions_test
 6/36 Test  #6: functions_test ...................   Passed    0.04 sec
      Start  7: math_test
 7/36 Test  #7: math_test ........................   Passed    0.09 sec
      Start  8: model_test
 8/36 Test  #8: model_test .......................   Passed    0.08 sec
      Start  9: model_compiler_test
 9/36 Test  #9: model_compiler_test ..............   Passed    6.03 sec
      Start 10: nodes_test
10/36 Test #10: nodes_test .......................   Passed   14.00 sec
      Start 11: passes_test
11/36 Test #11: passes_test ......................   Passed    0.10 sec
      Start 12: predictors_test
12/36 Test #12: predictors_test ..................   Passed    0.06 sec
      Start 13: trainers_test
13/36 Test #13: trainers_test ....................   Passed    0.04 sec
      Start 14: utilities_test
14/36 Test #14: utilities_test ...................   Passed    1.15 sec
      Start 15: cntk_importer_test
15/36 Test #15: cntk_importer_test ...............***Failed    0.81 sec
      Start 16: darknet_importer_test
16/36 Test #16: darknet_importer_test ............***Exception: Exit code 0xc0000409
  2.16 sec
      Start 17: forestTrainer_test
17/36 Test #17: forestTrainer_test ...............   Passed    0.07 sec
      Start 18: linearTrainer_test_0
18/36 Test #18: linearTrainer_test_0 .............   Passed    0.07 sec
      Start 19: linearTrainer_test_1
19/36 Test #19: linearTrainer_test_1 .............   Passed    0.06 sec
      Start 20: linearTrainer_test_2
20/36 Test #20: linearTrainer_test_2 .............   Passed    0.03 sec
      Start 21: linearTrainer_test_3
21/36 Test #21: linearTrainer_test_3 .............   Passed    0.04 sec
      Start 22: linearTrainer_test_4
22/36 Test #22: linearTrainer_test_4 .............   Passed    0.04 sec
      Start 23: linearTrainer_test_5
23/36 Test #23: linearTrainer_test_5 .............   Passed    0.04 sec
      Start 24: linearTrainer_test_6
24/36 Test #24: linearTrainer_test_6 .............   Passed    0.04 sec
      Start 25: linearTrainer_test_7
25/36 Test #25: linearTrainer_test_7 .............   Passed    0.03 sec
      Start 26: linearTrainer_test_8
26/36 Test #26: linearTrainer_test_8 .............   Passed    0.04 sec
      Start 27: linearTrainer_test_9
27/36 Test #27: linearTrainer_test_9 .............   Passed    0.04 sec
      Start 28: linearTrainer_test_10
28/36 Test #28: linearTrainer_test_10 ............   Passed    0.03 sec
      Start 29: protoNNTrainer_test_0
29/36 Test #29: protoNNTrainer_test_0 ............   Passed    0.25 sec
      Start 30: sweepingSGDTrainer_test
30/36 Test #30: sweepingSGDTrainer_test ..........   Passed    0.08 sec
      Start 31: apply_test
31/36 Test #31: apply_test .......................   Passed    0.07 sec
      Start 32: compile_test1
32/36 Test #32: compile_test1 ....................   Passed    0.11 sec
      Start 33: compile_test2
33/36 Test #33: compile_test2 ....................   Passed    0.05 sec
      Start 34: make_profiler_test
34/36 Test #34: make_profiler_test ...............***Failed   49.90 sec
      Start 35: wrap-test
35/36 Test #35: wrap-test ........................   Passed   43.15 sec
      Start 36: ell-python-interface-test
36/36 Test #36: ell-python-interface-test ........***Exception: Illegal  0.63 sec

89% tests passed, 4 tests failed out of 36

Total Test time (real) = 124.21 sec

The following tests FAILED:
         15 - cntk_importer_test (Failed)
         16 - darknet_importer_test (Exit code 0xc0000409
)
         34 - make_profiler_test (Failed)
         36 - ell-python-interface-test (ILLEGAL)
Errors while running CTest

**Comment by julian0001** [comment]
This is my output of ctest:

(py36) C:\Users\Julian\Documents\ELL\ELL.git\trunk\build>ctest --build-config Release
Test project C:/Users/Julian/Documents/ELL/ELL.git/trunk/build
      Start  1: common_test
 1/36 Test  #1: common_test ......................   Passed    0.29 sec
      Start  2: data_test
 2/36 Test  #2: data_test ........................   Passed    0.03 sec
      Start  3: dsp_test
 3/36 Test  #3: dsp_test .........................   Passed    3.62 sec
      Start  4: emitters_test
 4/36 Test  #4: emitters_test ....................   Passed    0.25 sec
      Start  5: evaluators_test
 5/36 Test  #5: evaluators_test ..................   Passed    0.03 sec
      Start  6: functions_test
 6/36 Test  #6: functions_test ...................   Passed    0.04 sec
      Start  7: math_test
 7/36 Test  #7: math_test ........................   Passed    0.09 sec
      Start  8: model_test
 8/36 Test  #8: model_test .......................   Passed    0.08 sec
      Start  9: model_compiler_test
 9/36 Test  #9: model_compiler_test ..............   Passed    6.03 sec
      Start 10: nodes_test
10/36 Test #10: nodes_test .......................   Passed   14.00 sec
      Start 11: passes_test
11/36 Test #11: passes_test ......................   Passed    0.10 sec
      Start 12: predictors_test
12/36 Test #12: predictors_test ..................   Passed    0.06 sec
      Start 13: trainers_test
13/36 Test #13: trainers_test ....................   Passed    0.04 sec
      Start 14: utilities_test
14/36 Test #14: utilities_test ...................   Passed    1.15 sec
      Start 15: cntk_importer_test
15/36 Test #15: cntk_importer_test ...............***Failed    0.81 sec
      Start 16: darknet_importer_test
16/36 Test #16: darknet_importer_test ............***Exception: Exit code 0xc0000409
  2.16 sec
      Start 17: forestTrainer_test
17/36 Test #17: forestTrainer_test ...............   Passed    0.07 sec
      Start 18: linearTrainer_test_0
18/36 Test #18: linearTrainer_test_0 .............   Passed    0.07 sec
      Start 19: linearTrainer_test_1
19/36 Test #19: linearTrainer_test_1 .............   Passed    0.06 sec
      Start 20: linearTrainer_test_2
20/36 Test #20: linearTrainer_test_2 .............   Passed    0.03 sec
      Start 21: linearTrainer_test_3
21/36 Test #21: linearTrainer_test_3 .............   Passed    0.04 sec
      Start 22: linearTrainer_test_4
22/36 Test #22: linearTrainer_test_4 .............   Passed    0.04 sec
      Start 23: linearTrainer_test_5
23/36 Test #23: linearTrainer_test_5 .............   Passed    0.04 sec
      Start 24: linearTrainer_test_6
24/36 Test #24: linearTrainer_test_6 .............   Passed    0.04 sec
      Start 25: linearTrainer_test_7
25/36 Test #25: linearTrainer_test_7 .............   Passed    0.03 sec
      Start 26: linearTrainer_test_8
26/36 Test #26: linearTrainer_test_8 .............   Passed    0.04 sec
      Start 27: linearTrainer_test_9
27/36 Test #27: linearTrainer_test_9 .............   Passed    0.04 sec
      Start 28: linearTrainer_test_10
28/36 Test #28: linearTrainer_test_10 ............   Passed    0.03 sec
      Start 29: protoNNTrainer_test_0
29/36 Test #29: protoNNTrainer_test_0 ............   Passed    0.25 sec
      Start 30: sweepingSGDTrainer_test
30/36 Test #30: sweepingSGDTrainer_test ..........   Passed    0.08 sec
      Start 31: apply_test
31/36 Test #31: apply_test .......................   Passed    0.07 sec
      Start 32: compile_test1
32/36 Test #32: compile_test1 ....................   Passed    0.11 sec
      Start 33: compile_test2
33/36 Test #33: compile_test2 ....................   Passed    0.05 sec
      Start 34: make_profiler_test
34/36 Test #34: make_profiler_test ...............***Failed   49.90 sec
      Start 35: wrap-test
35/36 Test #35: wrap-test ........................   Passed   43.15 sec
      Start 36: ell-python-interface-test
36/36 Test #36: ell-python-interface-test ........***Exception: Illegal  0.63 sec

89% tests passed, 4 tests failed out of 36

Total Test time (real) = 124.21 sec

The following tests FAILED:
         15 - cntk_importer_test (Failed)
         16 - darknet_importer_test (Exit code 0xc0000409
)
         34 - make_profiler_test (Failed)
         36 - ell-python-interface-test (ILLEGAL)
Errors while running CTest
