### ISSUE TITLE
ModuleNotFoundError: No module named '_model' when running call_model.py

### ISSUE THREAD

**Issue by kunhung** [microsoft/ELL#240]
Hi,

while following steps Win 10from https://microsoft.github.io/ELL/tutorials/Getting-started-with-image-classification-on-the-Raspberry-Pi/ on Win 10 x64 machine, 

C:\azsphere\ELL-master\build\host>python call_model.py
Traceback (most recent call last):
  File "call_model.py", line 8, in <module>
    import model
  File "C:\azsphere\ELL-master\build\host\model.py", line 11, in <module>
    import _model
ModuleNotFoundError: No module named '_model'

my built files under "host" folder are uploaded to https://www.dropbox.com/s/64zg0orbjsmnr4l/host.zip?dl=0, please help. Thanks!

Ken

**Comment by clovett** [comment]
If you look at this binary:
```
depends model\build\release\_model.pyd
```
it depends on Python 3.7 and vcruntime 140_1.dll.  My Anaconda environment uses Python 3.6, so if I rename your "host" folder to "model" and rebuilt it using VS 2019 and Python 3.6 then I can do this:
```
(ell) C:\Users\Chris\Downloads\host>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import model
Importing model
```
This works because there is an "__init__.py" file which adds build/release to the python sys path.
