### ISSUE TITLE
cntkDemo.py 'lastPrediction' referenced before assignment

### ISSUE THREAD

**Issue by hiramf** [Microsoft/ELL#58]
```
...Finished constructing ELL layers.
Traceback (most recent call last):
  File "cntkDemo.py", line 67, in <module>
    main()
  File "cntkDemo.py", line 53, in main
    if (text != lastPrediction):
UnboundLocalError: local variable 'lastPrediction' referenced before assignment
```

Surface Pro 3, i5 8GB, Windows 10
Anaconda3

**Comment by hiramf** [comment]
Found the problem. Line 33 in cntkDemo.py defines the wrong variable.
`last_prediction = "" `
should be 
`lastPrediction = "" `
